"""Add created field

Revision ID: a7c485e52d25
Revises: 9da2e52e975c
Create Date: 2022-03-13 15:48:13.135371

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a7c485e52d25"
down_revision = "9da2e52e975c"
branch_labels = None
depends_on = None


def upgrade():
    current_time = datetime.utcnow().isoformat("T")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("created", sa.DateTime(), nullable=True))
    op.add_column("posts", sa.Column("created", sa.DateTime(), nullable=True))
    op.execute(f"UPDATE comments SET created = {current_time};")
    op.execute(f"UPDATE posts SET created = {current_time};")
    op.alter_column("comments", sa.Column("created", sa.DateTime(), nullable=False))
    op.alter_column("posts", sa.Column("created", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "created")
    op.drop_column("comments", "created")
    # ### end Alembic commands ###
